some_file: other_file1 other_file2 other_file3
	@echo "some_file"
	@echo $@
	@echo $?
	@echo $^
	@touch some_file

other_file1:
	@echo "other_file1"
	@touch other_file1

other_file2:
	@echo "other_file2"
	@touch other_file2

other_file3:
	@echo "other_file3"
	@touch other_file3






